# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2bcdee49788632f62a5f17b28a3f0475e19c75988e77fe6f210489967efe81463f9df9429ee6b7f509b33e09ca209ed144e45430ec09e9535c01aff4f712897

test:
  secret_key_base: a4e9ebe5b06cc17dda902f549cf814f2e515906a0459f0bc84e745bba6bb8463d390fac0761c8fc45d7773235802cf715dad5afe01f1663cb4708e66f51e1394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
