# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf7d815c89182066167960107e8119823ace38755295d4a2c37a6ca5b500727a8a4d9a3655a06037e23d885f933a52fe4214969ad0592f0daccbbdaebfd10ae

test:
  secret_key_base: c8d2d6866c27a12003ec2084397f7da25e6fcefc24ccdde25a5a4c1d9f222898e5d5fa7d2bf4c31c33f5edf45cd1934b5b5390c72c15d986d00933202be2b5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
